// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUlh099vMd3wc9z2fJJkUJDvv-XrXfa-E',
    appId: '1:54336526360:web:33496e5f314afb3f220b6d',
    messagingSenderId: '54336526360',
    projectId: 'peliculas-flutter-2026',
    authDomain: 'peliculas-flutter-2026.firebaseapp.com',
    storageBucket: 'peliculas-flutter-2026.firebasestorage.app',
    measurementId: 'G-D1XFSV7ZS5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3WcGVa4mKTVyB9aGlhjN6iByLsvpMdUc',
    appId: '1:54336526360:android:6d50ea2d8145be96220b6d',
    messagingSenderId: '54336526360',
    projectId: 'peliculas-flutter-2026',
    storageBucket: 'peliculas-flutter-2026.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUlh099vMd3wc9z2fJJkUJDvv-XrXfa-E',
    appId: '1:54336526360:web:a032e0225bd77cde220b6d',
    messagingSenderId: '54336526360',
    projectId: 'peliculas-flutter-2026',
    authDomain: 'peliculas-flutter-2026.firebaseapp.com',
    storageBucket: 'peliculas-flutter-2026.firebasestorage.app',
    measurementId: 'G-QWM8SXRWGB',
  );

}